// Font Awesome Configuration
import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faSearch,
    faMapMarkerAlt,
    faList,
    faBriefcase,
    faBuilding,
    faUsers,
    faClock,
    faHeart,
    faBookmark,
    faShare,
    faArrowRight,
    faArrowLeft,
    faChevronRight,
    faChevronLeft,
    faChevronDown,
    faTimes,
    faCheck,
    faBars,
    faHome,
    faEnvelope,
    faPhone,
    faGlobe,
    faStar,
    faFilter,
    faSort,
    faEye,
    faEdit,
    faTrash,
    faPlus,
    faMinus,
    faSpinner,
    faExclamationCircle,
    faCheckCircle,
    faInfoCircle,
    faUser,
    faCog,
    faSignOutAlt,
    faBell,
    faComment,
    faComments,
    faPaperPlane,
    faDownload,
    faUpload,
    faFile,
    faFileAlt,
    faImage,
    faVideo,
    faLink,
    faExternalLinkAlt,
    faCalendar,
    faCalendarAlt,
    faMoneyBillWave,
    faGraduationCap,
    faLaptopCode,
    faPalette,
    faChartLine,
    faBullhorn,
    faHandshake,
    faUserTie,
    faIndustry,
    faMapMarked,
} from '@fortawesome/free-solid-svg-icons';

import {
    faHeart as faHeartRegular,
    faBookmark as faBookmarkRegular,
    faClock as faClockRegular,
    faUser as faUserRegular,
    faEnvelope as faEnvelopeRegular,
} from '@fortawesome/free-regular-svg-icons';

import {
    faFacebook,
    faTwitter,
    faLinkedin,
    faGithub,
    faGoogle,
    faInstagram,
} from '@fortawesome/free-brands-svg-icons';

// Add icons to library
library.add(
    // Solid icons
    faSearch,
    faMapMarkerAlt,
    faList,
    faBriefcase,
    faBuilding,
    faUsers,
    faClock,
    faHeart,
    faBookmark,
    faShare,
    faArrowRight,
    faArrowLeft,
    faChevronRight,
    faChevronLeft,
    faChevronDown,
    faTimes,
    faCheck,
    faBars,
    faHome,
    faEnvelope,
    faPhone,
    faGlobe,
    faStar,
    faFilter,
    faSort,
    faEye,
    faEdit,
    faTrash,
    faPlus,
    faMinus,
    faSpinner,
    faExclamationCircle,
    faCheckCircle,
    faInfoCircle,
    faUser,
    faCog,
    faSignOutAlt,
    faBell,
    faComment,
    faComments,
    faPaperPlane,
    faDownload,
    faUpload,
    faFile,
    faFileAlt,
    faImage,
    faVideo,
    faLink,
    faExternalLinkAlt,
    faCalendar,
    faCalendarAlt,
    faMoneyBillWave,
    faGraduationCap,
    faLaptopCode,
    faPalette,
    faChartLine,
    faBullhorn,
    faHandshake,
    faUserTie,
    faIndustry,
    faMapMarked,
    // Regular icons
    faHeartRegular,
    faBookmarkRegular,
    faClockRegular,
    faUserRegular,
    faEnvelopeRegular,
    // Brand icons
    faFacebook,
    faTwitter,
    faLinkedin,
    faGithub,
    faGoogle,
    faInstagram
);

// Icon mapping for easy access
export const icons = {
    search: 'search',
    location: 'map-marker-alt',
    list: 'list',
    briefcase: 'briefcase',
    building: 'building',
    users: 'users',
    clock: 'clock',
    heart: 'heart',
    heartRegular: ['far', 'heart'],
    bookmark: 'bookmark',
    bookmarkRegular: ['far', 'bookmark'],
    share: 'share',
    arrowRight: 'arrow-right',
    arrowLeft: 'arrow-left',
    chevronRight: 'chevron-right',
    chevronLeft: 'chevron-left',
    chevronDown: 'chevron-down',
    times: 'times',
    check: 'check',
    bars: 'bars',
    home: 'home',
    envelope: 'envelope',
    phone: 'phone',
    globe: 'globe',
    star: 'star',
    filter: 'filter',
    sort: 'sort',
    eye: 'eye',
    edit: 'edit',
    trash: 'trash',
    plus: 'plus',
    minus: 'minus',
    spinner: 'spinner',
    exclamationCircle: 'exclamation-circle',
    checkCircle: 'check-circle',
    infoCircle: 'info-circle',
    user: 'user',
    cog: 'cog',
    signOut: 'sign-out-alt',
    bell: 'bell',
    comment: 'comment',
    comments: 'comments',
    paperPlane: 'paper-plane',
    download: 'download',
    upload: 'upload',
    file: 'file',
    fileAlt: 'file-alt',
    image: 'image',
    video: 'video',
    link: 'link',
    externalLink: 'external-link-alt',
    calendar: 'calendar',
    calendarAlt: 'calendar-alt',
    money: 'money-bill-wave',
    graduation: 'graduation-cap',
    laptop: 'laptop-code',
    palette: 'palette',
    chart: 'chart-line',
    bullhorn: 'bullhorn',
    handshake: 'handshake',
    userTie: 'user-tie',
    industry: 'industry',
    mapMarked: 'map-marked',
    // Brands
    facebook: ['fab', 'facebook'],
    twitter: ['fab', 'twitter'],
    linkedin: ['fab', 'linkedin'],
    github: ['fab', 'github'],
    google: ['fab', 'google'],
    instagram: ['fab', 'instagram'],
} as const;
